### ISSUE TITLE
Duda sobre PBT y fallos en tests

### ISSUE THREAD

**Issue by ivanAsensioVazquez** [UDC-FIC-VVS/sistema-de-correo-electronico-ivanAsensioVazquez#3]
Me preguntaba como podía ejecutar la propiedad PBT que he añadido llamada ArchivadorSimpleProperty, es decir se ejecutan como JUnit o como se comprueba?
Por cierto, no entiendo la razón pero todos los tests relacionados con los métodos de Previsualización me fallan, estoy utilizando el debugger y estoy poniendo el mismo valor para ver si era un error en el valor, pero ni copiandolo funciona

**Comment by lauramcastro** [comment]
Vexo que usaches JUnit-QuickCheck así que a propiedade debería executarse simplemente como o resto de probas.

Se cadra JUnit non considera a túa clase porque lle chamaches `ArchivadorSimpleProperty` e JUnit agarda que as clases de proba se chamen `*Test`... podes ou renomear a clase ou modificar a configuración de JUnit no `pom.xml`, o que prefiras.

Pecha a issue se con iso resolves o problema.
