### ISSUE TITLE
Duda sobre tests diferentes a dinámicos caja negra

### ISSUE THREAD

**Issue by ivanAsensioVazquez** [UDC-FIC-VVS/sistema-de-correo-electronico-ivanAsensioVazquez#4]
Buenas Laura:
Me preguntaba como te mostramos los tests, ya sea con spotbugs o con checkstyle, ya que en mi caso los estoy realizando con los plugins que hay en eclipse.
Además he añadido un test de arquitectura con archUnit y tengo dudas sobre que poner como clases en este método:

JavaClasses importedClasses = new ClassFileImporter().importPackages("gal.udc.fic.vvs");

Un saludo.

**Comment by lauramcastro** [comment]
Ola, Iván:

Aínda que ti persoalmente os fagas desde o teu IDE de preferencia, deberías incluír as dependencias desas ferramentas no pom que está no repositorio, para que calquera poida executalas.

No referente a ArchUnit, non sei se entendo moi ben a túa dúbida. Trátase dunha ferramenta que nos axuda a detectar violacións da estrutura dos diferentes paquetes, é dicir, por exemplo, o uso de subclases concretas no canto de interfaces públicas por parte de obxectos que están noutros paquetes.

Confío en que isto aclare o que preguntabas. Se é así, pecha ti mesmo a _issue_.
